# Generated by Django 5.1.7 on 2025-03-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
