# Generated by Django 5.1.7 on 2025-03-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='12.30pm'),
            preserve_default=False,
        ),
    ]
