# Generated by Django 5.1.7 on 2025-03-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_contact_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
