# Generated by Django 5.1.7 on 2025-03-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactform',
        ),
    ]
