# Generated by Django 5.1.7 on 2025-03-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_contact_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactform',
        ),
    ]
